# Generated by Django 6.0.6 on 2026-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(default='https://learner.saveetha.in/')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=255)),
                ('automation_enabled', models.BooleanField(default=False)),
                ('headless', models.BooleanField(default=False)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('refresh_interval', models.PositiveIntegerField(default=30)),
                ('preferred_event', models.CharField(blank=True, max_length=150)),
                ('preferred_slot', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('slot', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
